#!/usr/bin/env bash
# This script displays bad, good luck and best school
COUNTER=1
while [ "$COUNTER" -le 10 ];
do
if [ "$COUNTER" -eq 4 ]
then
	echo "bad luck"
	(( COUNTER += 1 ))
elif [ "$COUNTER" -eq 8 ]
then
	echo "good luck"
	(( COUNTER += 1 ))
else
	echo "Best School"
	(( COUNTER += 1 ))
fi
done
